# corresponded to 1.25.4
FROM golang@sha256:6ca9eb0b32a4bd4e8c98a4a2edf2d7c96f3ea6db6eb4fc254eef6c067cf73bb4

WORKDIR /workspace/golang-app
COPY . .
ARG GO_LDFLAGS=""
RUN CGO_ENABLED=0 GOOS=linux GO111MODULE=on make build

ENTRYPOINT [ "/workspace/golang-app/http-server" ]