FROM registry.access.redhat.com/ubi9:latest AS rust-builder
ARG TARGETARCH

RUN echo Target architecture: ${TARGETARCH}

COPY . /opt/app-root/src/
WORKDIR /opt/app-root/src/insights-runtime-extractor

USER 0
ENV HOME="/root"
ENV PATH="${HOME}/.cargo/bin:${HOME}/.local/bin:${PATH}"

RUN chgrp root /opt/app-root/src/insights-runtime-extractor && \
    chmod g+w /opt/app-root/src/insights-runtime-extractor && \
    dnf install -y gcc make rust-toolset rustfmt

RUN find $HOME/. -type d -exec chmod 777 {} \; && \
    find $HOME/. -type f -exec chmod ugo+rw {} \;

USER 1001