FROM registry.access.redhat.com/ubi9:latest AS rust-builder
ARG TARGETARCH

RUN echo Target architecture: ${TARGETARCH}

ENV RUST_TOOLCHAIN=1.81.0

COPY . /opt/app-root/src/
WORKDIR /opt/app-root/src/insights-runtime-extractor

USER 0
ENV HOME="/root"
ENV PATH="${HOME}/.cargo/bin:${HOME}/.local/bin:${PATH}"

RUN chgrp root /opt/app-root/src/insights-runtime-extractor && \
    chmod g+w /opt/app-root/src/insights-runtime-extractor && \
    dnf install -y gcc make

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain ${RUST_TOOLCHAIN}
RUN if [ "$TARGETARCH" == "arm64" ]; then rustup target add aarch64-unknown-linux-musl; fi
RUN if [ "$TARGETARCH" == "amd64" ]; then rustup target add x86_64-unknown-linux-musl; fi

RUN mkdir -p $HOME/.cargo/git/ && \
    find $HOME/. -type d -exec chmod 777 {} \; && \
    find $HOME/. -type f -exec chmod ugo+rw {} \;

USER 1001