FROM registry.ci.openshift.org/ocp/4.21:base-rhel9 AS rust-builder
ARG TARGETARCH

RUN dnf update -y && dnf -y install \
    gcc make wget rust-toolset rustfmt

WORKDIR /workspace/extractor
COPY extractor .
RUN make TARGETARCH=${TARGETARCH}

FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.24-openshift-4.21 AS go-builder

WORKDIR /workspace/fingerprints
COPY fingerprints .
ARG GO_LDFLAGS=""
ENV GOEXPERIMENT=strictfipsruntime
RUN CGO_ENABLED=0 GOOS=linux GO111MODULE=on make build

FROM registry.ci.openshift.org/ocp/4.21:base-rhel9

RUN dnf update -y && dnf -y install \
    cri-tools

COPY --from=rust-builder /workspace/extractor/config/ /
COPY --from=rust-builder /workspace/extractor/target/release/extractor_server /extractor_server
COPY --from=rust-builder /workspace/extractor/target/release/coordinator /coordinator
# Copy fingerprints written in Go
COPY --from=go-builder --chmod=755 /workspace/fingerprints/bin/fpr_* /
ENTRYPOINT [ "/extractor_server" ]