# OpenShift Insights Runtime Extractor
:toc:

This repository provides a mechanism to gather runtime info from containers to get additional insights on user workloads and make investment decisions that will drive utilization.

The container images built from this repository provides an `insights-runtime-extractor`
feature integrated to the https://github.com/openshift/insights-operator/tree/master[OpenShift Insights Operator].

This feature was proposed and approved by https://github.com/openshift/enhancements/blob/master/enhancements/insights/insights-runtime-extractor.md[this enhancement].

The container image is published at `ghcr.io/jmesnil/insights-runtime-extractor:latest`

## Build the container image for development

[source,bash]
----
./scripts/build.sh
----

It builds a multi-arch (ARM64 & AMD64) image named `quay.io/jmesnil/insights-runtime-extractor:latest`.

## Build the development image

[source,bash]
----
./scripts/build-dev.sh
----

This creates a `rust-dev` Container image that contains all the Rust plumbing to compile and execute the code

## Run the development image and compile the Rust code base

[source,bash]
----
./scripts/rust-dev.sh

# you are then inside a container ready to compile the Rust code
make
----
