# OpenShift Insights Runtime Extractor
:toc:

This repository provides a mechanism to gather runtime info from containers to get additional insights on user workloads and make investment decisions that will drive utilization.

The container images built from this repository provides an `insights-runtime-extractor`
feature integrated to the https://github.com/openshift/insights-operator/tree/master[OpenShift Insights Operator].

This feature was proposed and approved by https://github.com/openshift/enhancements/blob/master/enhancements/insights/insights-runtime-extractor.md[this enhancement].

## Build the container image

[source,bash]
----
make build-image
----

It builds a multi-arch (ARM64 & AMD64) image named `quay.io/jmesnil/insights-operator-runtime:latest`.

## Build the development image

[source,bash]
----
make build-dev-image
----

This creates a `rust-dev` Container image that contains all the Rust plumbing to compile and execute the code

## Run the development image and compile the Rust code base

[source,bash]
----
make rust-dev

# you are then inside a container ready to compile the Rust code
make
----
>>>>>>> 1724a3e (initial import)
