.PHONY: golang-app quarkus-3.13.0 quarkus-3.15.1 spring-boot plain-java

all: quarkus-3.13.0 quarkus-3.15.1 spring-boot golang-app plain-java

golang-app:
	cd ./golang-app && make

quarkus-3.13.0:
	cd ./quarkus/3.13.0. && make

quarkus-3.15.1:
	cd ./quarkus/3.15.1 && make

spring-boot:
	cd ./spring-boot && make

plain-java:
	cd ./plain-java && make