.PHONY: golang-app-1.22.6 golang-app-1.24.1 golang-app-1.25.4 quarkus-3.13.0 quarkus-3.15.1 quarkus-3.19.3 quarkus-3.24.4 quarkus-3.29.2 spring-boot-3.1.4 spring-boot-3.4.3 spring-boot-3.5.3 plain-java-17.0.13 plain-java-24.0.1 plain-java-25.0.1 python-app-2.7.18 python-app-3.9.19 python-app-3.13.2 python-app-3.14.0 nodejs-app-22.6.0 nodejs-app-22.14.0 nodejs-app-24.4.1 nodejs-app-25.1.0 RHBQ-3.8.6 RHBQ-3.15.3 RHBQ-3.20.1 RHBQ-3.27.0 debian-11 debian-12 debian-13 oracle-linux-8 oracle-linux-10

all: quarkus-3.13.0 quarkus-3.15.1 quarkus-3.19.3 quarkus-3.24.4 quarkus-3.29.2 spring-boot-3.1.4 spring-boot-3.4.3 spring-boot-3.5.3 golang-app-1.22.6 golang-app-1.24.1 golang-app-1.25.4 plain-java-17.0.13 plain-java-24.0.1 plain-java-25.0.1 python-app-2.7.18 python-app-3.9.19 python-app-3.13.2 python-app-3.14.0 nodejs-app-22.6.0 nodejs-app-22.14.0 nodejs-app-24.4.1 nodejs-app-25.1.0 RHBQ-3.8.6 RHBQ-3.15.3 RHBQ-3.20.1 RHBQ-3.27.0 debian-11 debian-12 debian-13 oracle-linux-8 oracle-linux-10

nodejs-app-22.6.0:
	cd ./nodejs/22.6.0 && make

nodejs-app-22.14.0:
	cd ./nodejs/22.14.0 && make

nodejs-app-24.4.1:
	cd ./nodejs/24.4.1 && make

nodejs-app-25.1.0:
	cd ./nodejs/25.1.0 && make

python-app-2.7.18:
	cd ./python/2.7.18 && make

python-app-3.9.19:
	cd ./python/3.9.19 && make
	
python-app-3.13.2:
	cd ./python/3.13.2 && make

python-app-3.14.0:
	cd ./python/3.14.0 && make

golang-app-1.22.6:
	cd ./golang-app/1.22.6 && make

golang-app-1.24.1:
	cd ./golang-app/1.24.1 && make

golang-app-1.25.4:
	cd ./golang-app/1.25.4 && make

quarkus-3.13.0:
	cd ./quarkus/3.13.0. && make

quarkus-3.15.1:
	cd ./quarkus/3.15.1 && make

quarkus-3.19.3:
	cd ./quarkus/3.19.3 && make

quarkus-3.24.4:
	cd ./quarkus/3.24.4 && make

quarkus-3.29.2:
	cd ./quarkus/3.29.2 && make

spring-boot-3.1.4:
	cd ./spring-boot/3.1.4 && make

spring-boot-3.4.3:
	cd ./spring-boot/3.4.3 && make

spring-boot-3.5.3:
	cd ./spring-boot/3.5.3 && make

RHBQ-3.8.6:
	cd ./RHBQ/3.8.6 && make

RHBQ-3.15.3:
	cd ./RHBQ/3.15.3 && make

RHBQ-3.20.1:
	cd ./RHBQ/3.20.1 && make

RHBQ-3.27.0:
	cd ./RHBQ/3.27.0 && make

plain-java-17.0.13:
	cd ./plain-java/17.0.13 && make

plain-java-24.0.1:
	cd ./plain-java/24.0.1 && make

plain-java-25.0.1:
	cd ./plain-java/25.0.1 && make

debian-11:
	cd ./debian/11 && make

debian-12:
	cd ./debian/12 && make

debian-13:
	cd ./debian/13 && make

oracle-linux-10:
	cd ./oracle-linux/10 && make

oracle-linux-8:
	cd ./oracle-linux/8 && make
