apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: insights-runtime-extractor
  labels:
    app.kubernetes.io/name: insights-runtime-extractor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: insights-runtime-extractor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: insights-runtime-extractor
    spec:
      serviceAccountName: insights-runtime-extractor-sa
      hostPID: true
      # Deploy the insights-runtime-extractor only on Linux worker nodes
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: exporter
          image: quay.io/openshift/origin-insights-runtime-exporter:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data
              name: data-volume
            - mountPath: /etc/tls
              name: insights-runtime-extractor-tls
              readOnly: true
          command:
            - /exporter
            - -bind
            - 0.0.0.0
            - -tls-cert
            - /etc/tls/tls.crt
            - -tls-server-name
            - exporter.openshift-insights.svc
        - name: extractor
          image: quay.io/openshift/origin-insights-runtime-extractor:latest
          imagePullPolicy: Always
          env:
            - name: CONTAINER_RUNTIME_ENDPOINT
              value: unix:///crio.sock
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_SYS_ADMIN
          volumeMounts:
            - mountPath: /crio.sock
              name: crio-socket
            - mountPath: /data
              name: data-volume
            - mountPath: /etc/tls/
              name: insights-runtime-extractor-tls
              readOnly: true
          command:
            - /extractor_server
            - --tls-cert
            - /etc/tls/tls.crt
            - --tls-key
            - /etc/tls/tls.key
      volumes:
        - name: crio-socket
          hostPath:
            path: /run/crio/crio.sock
            type: Socket
        - name: data-volume
          emptyDir: {}
        - name: insights-runtime-extractor-tls
          secret:
            secretName: insights-runtime-extractor-tls