apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: insights-runtime-extractor
  labels:
    app.kubernetes.io/name: insights-runtime-extractor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: insights-runtime-extractor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: insights-runtime-extractor
    spec:
      serviceAccountName: insights-runtime-extractor-sa
      hostPID: true
      # Deploy the insights-runtime-extractor only on Linux worker nodes
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: exporter
          image: quay.io/jmesnil/insights-runtime-exporter:latest
          imagePullPolicy: Always
          command:
            - /exporter
            - -bind
            - 0.0.0.0
            - -tls-cert
            - /etc/tls/private/tls.crt
            - -tls-key
            - /etc/tls/private/tls.key
            - -tls-ca
            - /var/run/configmaps/service-ca-bundle/service-ca.crt
            - -tls-server-name
            - localhost
          volumeMounts:
            - mountPath: /data
              name: data-volume
            - mountPath: /etc/tls/private
              name: insights-runtime-extractor-tls
              readOnly: true
            - mountPath: /var/run/configmaps/service-ca-bundle
              name: service-ca-bundle
              readOnly: true
        - name: extractor
          image: quay.io/jmesnil/insights-runtime-extractor:latest
          imagePullPolicy: Always
          env:
            - name: CONTAINER_RUNTIME_ENDPOINT
              value: unix:///crio.sock
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_SYS_ADMIN
          command:
            - /extractor_server
            - --tls-cert
            - /etc/tls/private/tls.crt
            - --tls-key
            - /etc/tls/private/tls.key
          volumeMounts:
            - mountPath: /crio.sock
              name: crio-socket
            - mountPath: /data
              name: data-volume
            - mountPath: /etc/tls/private
              name: insights-runtime-extractor-tls
              readOnly: true
      volumes:
        - name: crio-socket
          hostPath:
            path: /run/crio/crio.sock
            type: Socket
        - name: data-volume
          emptyDir: {}
        - name: insights-runtime-extractor-tls
          secret:
            secretName: insights-runtime-extractor-tls
        - name: service-ca-bundle
          configMap:
            name: service-ca-bundle