= Getting Started with JBoss EAP 8 on OpenShift


== The Application
The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Deploying the Quickstart
Make sure you have done all the https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#prerequisites[prerequisites] and https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#selecting_creating_a_project[selected/created a project].

Then install the Helm chart for EAP 8 to install the application into OpenShift.
[source,shell]
----
helm install eap8  --repo https://jbossas.github.io/eap-charts/ eap8
----
See the https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#deploying_with_helm[Deploying with Helm] section for information about when the application will be ready.

== Running the application

To run the application, you can access it through its OpenShift route:

[source,shell]
----
echo https://$(oc get route eap8 --template='{{ .spec.host }}')
----

If you use this URL, you will see the welcome page of the application.

== Explaining the application configuration

This application is extremely simple, so apart from the standard information in https://github.com/jboss-eap-up-and-running/docs/blob/main/RUNNING_ON_OPENSHIFT.adoc#introduction_to_helm_charts[Introduction to Helm Charts], it does not require any additional information.
