# Eclipse Temurin 26.0.1_8-jdk-ubi10-minimal
FROM eclipse-temurin@sha256:753634b50e80662e3fee5ee38c6436663cf23596a13008f8499208f18f97f578
COPY target/plain-java-0.0.1-SNAPSHOT-jar-with-dependencies.jar /plain-java-app.jar
ENTRYPOINT ["java","-jar","/plain-java-app.jar"]