# Red Hat OpenJDK 21
FROM registry.access.redhat.com/ubi8/openjdk-21@sha256:7aaabadcb6bbcc3783d3f5d0685037797efbb7a590088dafab7927414fe93a37
WORKDIR /app
COPY target/rest-service-complete-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]
