# corresponded to 1.26.3
FROM golang@sha256:2d6c80227255c3112a4d08e67ba98e58efd3846daf15d9d7d4c389565d881b1a

WORKDIR /workspace/golang-app
COPY . .
ARG GO_LDFLAGS=""
RUN CGO_ENABLED=0 GOOS=linux GO111MODULE=on make build

ENTRYPOINT [ "/workspace/golang-app/http-server" ]